defaults:
  -
    scope:
      path: "jekyll_blogposts"
    values:
      permalink: "articles/:year/:month/:day/:title:output_ext"
  -
    scope:
      path: "jekyll_motsdupresident"
    values:
      permalink: "mots-du-president/:pathid"
