defaults:
  -
    scope:
      path: "jekyll_blogposts"
    values:
      permalink: "articles/:year/:month/:day/:title:output_ext"
  -
    scope:
      path: "jekyll_motsdupresident"
    values:
      permalink: "mots-du-president/:pathid"
  -
    scope:
      path: "jekyll_antennes"
    values:
      layout: "antenne"
  -
    scope:
      path: "jekyll_redirections"
    values:
      layout: "redirect"
  -
    scope:
      path: "jekyll_partenaires"
    values:
      layout: "partenaire"
      permalink: "partenaires/:title"
